ServerName web.fis.epn.edu.ec

<VirtualHost *:443>
    ServerName web.fis.epn.edu.ec

    SSLEngine on
    SSLCertificateFile /etc/apache2/tls/web.cert.pem
    SSLCertificateKeyFile /etc/apache2/tls/web.key.pem

    SSLProtocol -all +TLSv1.2 +TLSv1.3

    Header always set Strict-Transport-Security "max-age=31536000"
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-Frame-Options "SAMEORIGIN"

    DocumentRoot /var/www/html

    <Directory /var/www/html>
        Options -Indexes
        Require all granted
    </Directory>

    ScriptAlias /secure/whoami /usr/lib/cgi-bin/whoami.cgi

    <Location /secure/whoami>
        AuthType GSSAPI
        AuthName "FIS Kerberos"
        GssapiCredStore keytab:/etc/apache2/web.keytab
        GssapiAllowedMech krb5
        GssapiSSLonly On
        GssapiLocalName Off
        Require valid-user
    </Location>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
